Marko_Ventures/Marko_Ventures/urls.py
from django.contrib import admin
from django.urls import path, include


urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('core.urls')),

]

Marko_Ventures/core/urls.py
from django.urls import path
from .views import (index, contact, signupPage,
                    ItemDetailView, home, loginPage, logoutPage)

app_name = 'core'

urlpatterns = [
    path('', index, name='index'),
    path('home/', home, name='home'),
    path('login/', loginPage, name='login'),
    path('logout/', logoutPage, name='logout'),
    path('signup/', signupPage, name='signup'),
    path('contact/', contact, name='contact'),
    path('product/<slug>/', ItemDetailView.as_view(), name='product'),
]

Marko_Ventures/core/models.py
from django.db import models
from cloudinary.models import CloudinaryField
from django.db.models.signals import pre_delete
import cloudinary
import cloudinary.uploader
from django.dispatch import receiver
from django.shortcuts import reverse

CATEGORIES = (
    ('A', 'animal'),
    ('C', 'crop')
)


class Item(models.Model):
    title = models.CharField(max_length=100)
    description = models.TextField()
    image = CloudinaryField('image')
    category = models.CharField(choices=CATEGORIES, max_length=1)
    date_created = models.DateTimeField(auto_now_add=True)
    slug = models.SlugField()


    def __str__(self):
        return f"{self.title}==================================>>>{self.date_created}"

    def get_absolute_url(self):
        return reverse('core:product', kwargs={
            'slug': self.slug
        })


@receiver(pre_delete, sender=Item)
def photo_delete(sender, instance, **kwargs):
    cloudinary.uploader.destroy(instance.image.public_id)

Marko_Ventures/core/forms.py
from django.contrib.auth.forms import UserCreationForm
from django.contrib.auth.models import User
from django import forms


class CreationUserForm(UserCreationForm):
    username = forms.CharField(required=True, widget=forms.TextInput(attrs={
        'class': 'form2__input',
        'type': "text",
        'placeholder': "Username",
        'id': "uname"}))
    email = forms.EmailField(required=True, widget=forms.TextInput(attrs={
        'class': 'form2__input',
        'type': "email",
        'placeholder': "Email  address",
        'id': "email"}))
    password1 = forms.CharField(required=True, widget=forms.TextInput(attrs={
        'class': 'form2__input',
        'type': "password",
        'placeholder': "Password",
        'id': "pass"}))
    password2 = forms.CharField(required=True, widget=forms.TextInput(attrs={
        'class': 'form2__input',
        'type': "password",
        'placeholder': "Re-enter password",
        'id': "pass2"}))

    class Meta:
        model = User
        fields = ('username', 'email', 'password1', 'password2')

Marko_Ventures/core/views.py
from django.shortcuts import render, redirect
from django.views.generic import DetailView
from .models import Item
from django.contrib import messages
from django.contrib.auth.models import User, auth

app_name = 'core'


def home(request):
    context = {
        'item': Item.objects.all()
    }
    return render(request, 'core/home.html', context)


def index(request):
    return render(request, 'core/index.html')


class ItemDetailView(DetailView):
    model = Item
    template_name = 'core/product.html'


def contact(request):
    return render(request, 'core/contact.html')


def loginPage(request):
    if request.method == 'POST':
        username = request.POST['username']
        password = request.POST['password']

        user = auth.authenticate(request, username=username, password=password)

        if user is not None:
            auth.login(request, user)
            return redirect('core:index')
        else:
            messages.info(request, 'Username OR Password is Incorrect')
            return redirect('core:login')
    else:
        return render(request, 'core/login.html')


def signupPage(request):
    if request.method == 'POST':
        username = request.POST['username']
        email = request.POST['email']
        password1 = request.POST['password1']
        password2 = request.POST['password2']

        if password1 == password2:
            if User.objects.filter(username=username).exists():
                messages.info(request, 'Username Already Exist')
            elif User.objects.filter(email=email).exists():
                messages.info(request, 'Email Address Already Exist')
            else:
                user = User.objects.create_user(
                    username=username, email=email, password=password1)
                user.save()
                messages.info(
                    request, 'Congrats!! Account created for ' + username)
                return redirect('core:login')

        else:
            messages.info(request, 'Passwords do not match')
            return redirect('core:signup')
        return redirect('/')

    else:
        return render(request, 'core/signup.html')


def logoutPage(request):
    auth.logout(request)
    return redirect('core:login')

Marko_Ventures/templates/core/base.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <link rel="stylesheet" href="{% static 'css/main.css' %}">
    <link rel="stylesheet" href="{% static 'css/icon_font_styles.css' %}">
    <link rel="shortcut icon" href="{% static 'images/favicon.png' %}" type="image/x-icon">
    <!-- <link href="https://fonts.googleapis.com/css?family=Lato:100,300,400,700,900" rel="stylesheet"> -->
    <title>Marko-Ventures</title>
</head>
<body>
    <div class="background">
       <div class="background__place-center">
            <ul class="background__list">
              {% if request.user.is_authenticated %}
                <li class="background__item"><a href="#section-about" class="background__link">About Marko</a></li>
                <li class="background__item"><a href="{% url 'core:contact' %}" class="background__link">Contact us</a></li>
                <li class="background__item"><a href="{{ object.get_absolute_url }}" class="background__link">Products We offer</a></li>
                <li class="background__item"><a href="{% url 'core:logout' %}" class="background__link" id="sign_up">Logout</a></li>
                {% else %}
                <li class="background__item"><a href="#section-about" class="background__link">About Marko</a></li>
                <li class="background__item"><a href="{% url 'core:contact' %}" class="background__link">Contact us</a></li>
                <li class="background__item"><a href="{% url 'core:signup' %}" class="background__link" id="sign_up">Sign up</a></li>
                <li class="background__item"><a href="{% url 'core:login' %}" class="background__link" id="sign_up">Login</a></li>
                {% endif %}
            </ul>
       </div>
    </div>

    <div class="navigation">
        <div class="navigation__logo-box">
            <a href="{% url 'core:index' %}">
                <img src="{% static 'images/logo-green-2x.png' %}" alt="" class="logo">
            </a>
        </div>

        <nav class="navigation__nav">
            <ul class="navigation__list">
              {% if request.user.is_authenticated %}
                <li class="navigation__item"><a href="#" class="navigation__link">About Marko</a></li>
                <li class="navigation__item"><a href="{{ object.get_absolute_url }}" class="navigation__link">Products</a></li>
                <li class="navigation__item"><a href="{% url 'core:contact' %}" class="navigation__link">Contact us</a></li>
                <li class="navigation__item"><a href="{% url 'core:logout' %}" class="navigation__link" id="sign_up">Logout</a></li>
                <li class="navigation__item"><span class="navigation__link">Hello, {{request.user}}</span></li>
              {% else %}
              <li class="navigation__item"><a href="#section-about" class="navigation__link">About Marko</a></li>
              <li class="navigation__item"><a href="{% url 'core:contact' %}" class="navigation__link">Contact us</a></li>
                <li class="navigation__item"><a href="{% url 'core:signup' %}" class="navigation__link" id="sign_up">Sign up</a></li>
                <li class="navigation__item"><a href="{% url 'core:login' %}" class="navigation__link" id="sign_up">Login</a></li>
              {% endif %}
            </ul>
        </nav>
        <input type="checkbox" class="navigation__check" id="check">
        <label for="check" class="check">
            <nav class="navigation__ham">
                <div class="navigation__ham--item"></div>
                <div class="navigation__ham--item"></div>
                <div class="navigation__ham--item"></div>
             </nav>
        </label>
    </div>
        {% block content %}

        {% endblock content %}
            <script src="{% static 'javascript/script.js' %}"></script>
            <script src="{% static 'javascript/smooth-scroll.js' %}"></script>

            <script>
                var scroll = new SmoothScroll('a[href*="#"]');
            </script>

    </body>
    </html>

Marko_Ventures/templates/core/contact.html
{% extends 'core/base.html' %}
{% load static %}
{% block content %}
    <main class="contact">
        <section class="contact__main">
            <div class="contact__main__text-box">
               <div class="contact__main__text-box--main u-margin-bottom--medium">
                    <p class="u-margin-bottom--smallest">Contact Us</p>
                    <span>Need to get in touch with mako ventures? we're all ears.</span>
               </div>



               <div class="contact__main__text-box--secondary u-margin-bottom--small">
                    <a href="tel:"><i class="icon-basic-smartphone"></i> Give us a call </a>
                    <a href="mailto:"><i class="icon-basic-mail-open-text"></i> send us an email</a>
                </div>
            </div>
        </section>
        <div class="contact__image"></div>
    </main>
{% endblock content %}

Marko_Ventures/templates/core/footer.html
<footer class="footer">
    <ul class="nav">
            <li class="nav__item"><a href="#" class="nav__link">Lorem ipsum dolor</a></li>
            <li class="nav__item"><a href="#" class="nav__link">Lorem ipsum dolor</a></li>
            <li class="nav__item"><a href="#" class="nav__link">Lorem ipsum dolor</a></li>
            <li class="nav__item"><a href="#" class="nav__link">Lorem ipsum dolor</a></li>
    </ul>
    <p class="copyright">
        &copy; Copyright 2020 by Marko-Agro-Ventures. Lorem ipsum, dolor sit amet consectetur adipisicing elit. Repellendus minima possimus, molestias, assumenda expedita deleniti eligendi, accusantium debitis adipisci non voluptates recusandae blanditiis magnam tempore laborum neque ipsa repellat cupiditate.
    </p>
</footer>

Marko_Ventures/templates/core/home.html
<!DOCTYPE html>
<html lang="en" dir="ltr">
  <head>
    <meta charset="utf-8">
    <title></title>
  </head>
  <body>
    {% for item in item %}
    <h1>{{ item.title }}</h1>
    <h3>{{ item.description }}</h3>
    <img src="{{ item.image.url }}" alt="">
    {{ item.get_category_display }}
    <a href="{{ item.get_absolute_url }}">Enter</a>
    {% endfor %}
  </body>
</html>

Marko_Ventures/templates/core/index.html
{% extends 'core/base.html' %}
{% load static %}
{% block content %}
    <div class="header" id="home">
        <div class="header__text-box">
            <h1 class="heading-primary">
                <span class="heading-primary--main">Marko Ventures</span>
                <span class="heading-primary--sub">Lorem ipsum dolor</span>
            </h1>

        </div>
    </div>

    <main>
        <section class="section-about" id="section-about">

           <div class="u-center-text u-margin-bottom--big">
                <h2 class="heading-secondary">
                    some crap about the history
                </h2>
           </div>
           <div class="grid--two">
               <div class="col-1-of-2">
                    <h2 class="heading-tertiary u-margin-bottom--small">something about mako ventures</h2>
                    <p class="paragraph">
                        Lorem ipsum dolor sit amet consectetur adipisicing elit. Eligendi, magnam? Aliquam iure ratione nemo, eaque, vitae laudantium cumque, ullam aspernatur recusandae odio quasi veritatis error. Optio dignissimos placeat molestiae ab!
                    </p>

                    <h2 class="heading-tertiary u-margin-bottom--small">bla bla venture you won't regret</h2>
                    <p class="paragraph">
                        Lorem ipsum dolor sit amet consectetur adipisicing elit. Eligendi, magnam? Aliquam iure ratione nemo, eaque, vitae laudantium cumque, ullam aspernatur recusandae odio quasi veritatis error. Optio dignissimos placeat molestiae ab!
                    </p>

                    <a href="#" class="btn--text">learn more &rarr;</a>
                </div>

              <div class="row">
                <div class="col-1-of-2">
                    <div class="composition">
                        <img src="{% static 'images/marko-index-photo2.jpg' %}" alt="Photo 1" class="composition__photo composition__photo--p1"/>
                        <img src="{% static 'images/marko-photo4.jpg' %}" alt="Photo 2" class="composition__photo composition__photo--p2"/>
                        <img src="{% static 'images/marko-photo6.jpg' %}" alt="Photo 3" class="composition__photo composition__photo--p3"/>
                     </div>
                 </div>
              </div>
           </div>
        </section>

        <section class="section-products" id="section-products">

            <div class="u-center-text u-margin-bottom--big">
                <h2 class="heading-secondary">
                    some of our products
                </h2>
           </div>

            <div class="row u-margin-bottom--big">
                <div class="col-1-of-4">
                    <div class="card">
                        <div class="card__side card__side--front">
                            <div class="card__picture card__picture--1">
                                &nbsp;
                            </div>

                            <h4 class="card__heading">
                                <span class="card__heading-span--1"> Heading Crop</span>
                                </h4>

                            <div class="card__details">
                               <p>
                                Lorem ipsum dolor sit amet consectetur adipisicing elit. Suscipit, illo aliquid ipsam nobis accusantium ratione quas adipisci eum commodi vel aspernatur laborum quos quam sed consequuntur, perferendis rem, obcaecati libero?
                               </p>

                            </div>
                        </div>

                    </div>
                 </div>
                 <div class="col-1-of-4">
                    <div class="card">
                        <div class="card__side card__side--front">
                            <div class="card__picture card__picture--2">
                                &nbsp;
                            </div>

                            <h4 class="card__heading">
                                <span class="card__heading-span--2"> Heading Crop</span>
                                </h4>

                            <div class="card__details">
                               <p>
                                Lorem ipsum dolor sit amet consectetur adipisicing elit. Suscipit,
                                illo aliquid ipsam nobis accusantium ratione quas adipisci eum commodi
                                vel aspernatur laborum quos quam sed consequuntur, perferendis rem, obcaecati libero?
                               </p>

                            </div>
                        </div>

                    </div>
                 </div>
                 <div class="col-1-of-4">
                    <div class="card">
                        <div class="card__side card__side--front">
                            <div class="card__picture card__picture--3">
                                &nbsp;
                            </div>

                            <h4 class="card__heading">
                                <span class="card__heading-span--3"> Heading Crop</span>
                                </h4>

                            <div class="card__details">
                               <p>
                                Lorem ipsum dolor sit amet consectetur adipisicing elit. Suscipit, illo aliquid ipsam nobis accusantium ratione quas adipisci eum commodi vel aspernatur laborum quos quam sed consequuntur, perferendis rem, obcaecati libero?
                               </p>

                            </div>
                        </div>

                    </div>
                 </div>
                 <div class="col-1-of-4">
                    <div class="card">
                        <div class="card__side card__side--front">
                            <div class="card__picture card__picture--4">
                                &nbsp;
                            </div>

                            <h4 class="card__heading">
                                <span class="card__heading-span--4"> Heading Crop</span>
                                </h4>

                            <div class="card__details">
                               <p>
                                Lorem ipsum dolor sit amet consectetur adipisicing elit. Suscipit, illo aliquid ipsam nobis accusantium ratione quas adipisci eum commodi vel aspernatur laborum quos quam sed consequuntur, perferendis rem, obcaecati libero?
                               </p>

                            </div>
                        </div>

                    </div>
                 </div>
            </div>

            <div class="u-center-text ">
                <a href="#" class="btn btn--green btn--cta btn--animated">Discover More</a>
            </div>

        </section>
    </main>
    {% include 'core/footer.html'%}
    {% endblock content %}

Marko_Ventures/templates/core/login.html
{% extends 'core/base.html' %}
{% load static %}
{% block content %}
    <section class="section-book" id="section-book">
        <div class="row">
            <div class="book">
                <div class="book__form">
                  {% for message in messages %}
                      <p>{{ message }}</p>
                  {% endfor %}
                  <form class="" action="{% url 'core:login' %}" method="post">
                    {% csrf_token %}
                      <div class="u-center-text u-margin-bottom--medium">
                          <h2 class="heading-secondary">
                              Login
                          </h2>
                      </div>
                    <div class="form__group">
                        <input type="text" name="username" class="form__input" placeholder="Username" id="uname" required>
                        <label for="uname" class="form__label">Username</label>
                    </div>

                      <div class="form__group u-margin-bottom--smallest">
                          <input type="password" name="password" class="form__input" placeholder="Password" id="pass" required>
                          <label for="pass" class="form__label">Password</label>
                      </div>

                      <div class="form__group ">
                          <span class="form__sign-up-anchor"><a href="{% url 'core:signup' %}">I dont have an account yet</a></span>
                      </div>

                      <div class="form-group">
                          <button class="btn btn--green btn--animated" type="submit">Login &rarr;</button>
                      </div>
                  </form>
                </div>
            </div>
        </div>
    </section>
{% endblock content %}

Marko_Ventures/templates/core/product.html
{% extends 'core/base.html' %}
{% load static %}
{% block content %}
    <section class="product-header u-margin-bottom--big">
        <div class="product-header__text-box">
            <h1 class="product-header__text">
                <span class="product-header__text--main">Our products</span>
                <span class="product-header__text--sub">Lorem ipsum dolor</span>
            </h1>
        </div>





        <figure class="product-header__slider">
            <div class="product-header__slider--1">1</div>
            <div class="product-header__slider--2">2</div>
            <div class="product-header__slider--3">3</div>
            <div class="product-header__slider--4">4</div>
            <div class="product-header__slider--5">5</div>
        </figure>
    </section>



    <main>
        <section class="section">
            <div class="u-center-text u-margin-bottom--big">
                <h2 class="heading-secondary">
                    here are some of our best sellers
                </h2>
           </div>

           <div class="section__products">
              <div class="section__products--1">
                1
              </div>


              <div class="section__products--2">
                2
              </div>
           </div>


        </section>
    </main>
{% endblock content %}

Marko_Ventures/templates/core/signup.html
{% extends 'core/base.html' %}
{% load static %}
{% block content %}
    <section class="section-book" id="section-book">
        <div class="row">
            <div class="book">
                  {{ form.errors }}
                <div class="book__form">
                    <form action="#" class="form2" method='post'>
                      {% csrf_token %}
                      <div class="u-center-text u-margin-bottom--small">
                          <h2 class="heading-secondary">
                              Sign up now
                          </h2>
                      </div>
                    <div class="form2__group u-margin-bottom--smallest">
                        <input type="text" name="username" class="form2__input" placeholder="Username" id="uname" required>
                        <label for="uname" class="form2__label">Username</label>
                    </div>

                      <div class="form2__group u-margin-bottom--smallest">
                          <input type="email" name="email" class="form2__input" placeholder="Email address" id="email" required>
                          <label for="email" class="form2__label">Email address</label>
                      </div>
                      <div class="form2__group u-margin-bottom--smallest">
                          <input type="password" name="password1" class="form2__input" placeholder="Password" id="pass" required>
                          <label for="pass" class="form2__label">Password</label>
                      </div>
                      <div class="form2__group u-margin-bottom--smallest">
                          <input type="password" name="password2" class="form2__input" placeholder="Re-enter password" id="pass2" required>
                          <label for="pass2" class="form2__label">Confirm password</label>
                      </div>

                      <div class="form2__group ">
                          <span class="form2__sign-up-anchor"><a href="{% url 'core:login' %}">I have an account already</a></span>
                      </div>

                      <div class="form2-group">
                          <button class="btn btn--green btn--animated" type="submit">Get started &rarr;</button>
                      </div>
                </form>
                </div>
            </div>
        </div>
    </section>
{% endblock content %}

Marko_Ventures/templates/product.html
{% load cloudinary %}
<!DOCTYPE html>
<html lang="en" dir="ltr">
  <head>
    <meta charset="utf-8">
    <title></title>
  </head>
  <body>
    <h1>{{ object.title }}</h1>
    <h3>{{ object.description }}</h3>
    <img src="{{ object.image.url }}" alt="">
    {{ object.get_category_display }}
  </body>
</html>